name: CI

on:
  pull_request:
    branches:
      - main
    
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build the project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run eslint
        run: npm run lint:check
      - name: Test and coverage
        run: echo ${{secrets.TEST_DB_HOST}} && npm run test
        env: 
          DB_HOST: ${{secrets.TEST_DB_HOST}}
          DB_PORT: ${{secrets.TEST_DB_PORT}}
          DB_USERNAME: ${{secrets.TEST_DB_USERNAME}}
          DB_PASSWORD: ${{secrets.TEST_DB_PASSWORD}}
          DB_NAME: ${{secrets.TEST_DB_NAME}}
          REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          JWKS_URI: ${{secrets.JWKS_URI}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      - name: Build Typescript
        run: npm run build
      - name: Sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}


  build-and-push-docker:
    name: Build and Push docker image
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: imjenil45/mernspace-c-auth-service
      IMAGE_TAG: build-${{github.run_number}}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 -f docker/prod/Dockerfile .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

